#index:
#    path: /
#    controller: App\Controller\DefaultController::index

home:
    path: /home
    controller: 'App\Controller\HomeController::home'  # Quote the controller string

register:
    path: /register
    controller: 'App\Controller\RegisterController::register'  # Quote the controller string
   
login:
    path: /login
    controller: 'App\Controller\SecurityController::login'  # Quote the controller string